name: CI for a springboot application

on:
    workflow_dispatch

jobs:
    build_test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout artifact
          uses: actions/checkout@v6

        - name: Setup-JDK
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'

        - name: Maven build and test
          working-directory: docker/app1-hello/springboot/hello-spring
          run: mvn -B clean verify

        - name: Upload test results
          uses: actions/upload-artifact@v4

          with:
            name: TestReport
            path: docker/app1-hello/springboot/hello-spring
            
    build:
            runs-on: ubuntu-latest
            steps:
            - name: Checkout artifact
              uses: actions/checkout@v6

            - name: Setup-JDK
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '21'

            - name: Build JAR for docker
              working-directory: docker/app1-hello/springboot/hello-spring
              run: mvn -B clean package -DskipTests

            - name: Login to Dockerhub
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            - name: push to Dockerhub
              uses: docker/build-push-action@v7
              with:
                push: true
                tags: ${{github.actor}}/spring-app:latest 
        

        


                    
        
          
