name: Secrets file Pipeline

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Hello message from creator
              env:
                creator_name: ${{secrets.creator_name}}
              run: echo "Hello from $creator_name"
        

